---
- hosts: load_generators
  any_errors_fatal: true
  remote_user: centos
  tasks:
  - name: go get gateload
    shell: GOPATH=/opt/go go get github.com/couchbaselabs/gateload
  - name: symlink gateload into /usr/local/bin
    file: src=/opt/go/bin/gateload dest=/usr/local/bin/gateload owner=centos group=centos state=link
    sudo: true
  - name: copy gateload config to host
    copy: src=files/gateload_config.json dest=/home/centos/gateload_config.json owner=centos group=centos mode=0644
  - name: sysctl file to increase available port range for outgoing socket connections
    copy: src=files/sysctld.conf dest=/etc/sysctl.d/20-increase-port-range.conf owner=root group=root mode=0644
    sudo: true
  - name: shell cmd to increase available port range for outgoing socket connections
    shell: sysctl --system
    sudo: true



