---
- hosts: sync_gateways
  remote_user: centos
  any_errors_fatal: true
  sudo: true
  tasks:
  - name: Collect sync gateway profile
    script: files/sync_gateway_collect_profile.sh /home/sync_gateway/sync_gateway /tmp
  - name: Fetch sync gateway profile
    fetch: src=/tmp/profile_data.tar.gz dest=/tmp/profile_data_by_server
  - name: Tell user where to find the profile data
    debug: msg="Profile data has been saved in /tmp/profile_data_by_server"

