---
- hosts: all
  connection: local
  any_errors_fatal: true
  tasks:
  - name: Create groups based on ec2 access key
    group_by: key=key_{{ ec2_key_name }}

- hosts: load_generators
  vars:
    ec2keyname: key_{{ ec2_key_name }}
  remote_user: centos
  any_errors_fatal: true
  sudo: yes

  tasks:

  - name: install git
    yum: pkg=git state=latest

  - name: install java
    yum: pkg=java-1.7.0-openjdk-devel

  - name: Create /opt directory
    file: path=/opt state=directory

  - name: Create /home/projects/sg-gatling-load/ directory
    file: path=/home/projects/sg-gatling-load/ state=directory

  - name: Download Maven3
    get_url: dest=/opt/maven3.tar.gz url=http://apache.proserve.nl/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz

  - name: Unpack Maven3
    action: command creates=/opt/maven chdir=/opt tar zxvf /opt/maven3.tar.gz

  - name: Create Maven3 directory link
    file: path=/opt/maven src=/opt/apache-maven-3.2.5 state=link

  - name: Set mvn link
    action: command update-alternatives --install /usr/bin/mvn mvn /opt/maven/bin/mvn 1

  - name: Remove all files in sg-gatling-load except 'themes' folder that could be already attached to splunk
    shell: cd /home/projects/sg-gatling-load/ && rm -rf .[^.] .??* && find ! -name 'themes' -type f -exec rm -f {} + && find ! -name 'themes' -type d -exec rm -rf {} + 2
    ignore_errors: yes

  - name: Checkout sg-gatling load project from github
    shell: cd /home/projects/sg-gatling-load && git init && git remote add origin https://github.com/couchbaselabs/sg-gatling-load.git && git fetch && git checkout -t origin/master

  - name: Remove somelog.txt before running theme
    file: path=/home/projects/sg-gatling-load/somelog.txt state=absent

  - name: Set sg-gatling-load baseURL for all themes
    lineinfile: 
      dest=/home/projects/sg-gatling-load/pom.xml 
      regexp='<simulation.targetHosts>.*</simulation.targetHosts>' 
      line='<simulation.targetHosts>{% set comma = joiner(",") %} {% for item in groups.sync_gateways | intersect(groups[ec2keyname]) -%} {{ comma() }}{{ hostvars[item].ec2_private_ip_address }} {%- endfor %}</simulation.targetHosts>'