---
- hosts: load_generators
  any_errors_fatal: true
  remote_user: centos

  # Kill gateload
  tasks:
  - name: kill previous gateload screen
    shell: screen -X -S gateload kill
    ignore_errors: yes
  - name: kill previous gateload_expvars screen
    shell: screen -X -S gateload_expvars kill
    ignore_errors: yes

- hosts: sync_gateways
  any_errors_fatal: true
  remote_user: centos
  sudo: true

  # Copy machine stat collection script to sync_gateways
  tasks:
  - name: copy the machine collection script
    copy: src=files/log_machine_stats.py dest=/home/sync_gateway/ owner=sync_gateway group=sync_gateway mode=755
    when: "'sync_gateway_index_writers' not in group_names"
  # Start collecting machine stats, run async with an hour timeout, no polling
  - name: start stat collection
    shell: ./log_machine_stats.py chdir=/home/sync_gateway/
    async: 3600
    poll: 0
    when: "'sync_gateway_index_writers' not in group_names"

  # Copy profile collection script to sync_gateways
  - name: copy the profile collection script
    copy: src=files/sync_gateway_collect_profile.py dest=/home/sync_gateway/ owner=sync_gateway group=sync_gateway mode=755
    when: "'sync_gateway_index_writers' not in group_names"
  # Start collecting profile, run async with an hour timeout, no polling
  - name: start profile collection
    shell: ./sync_gateway_collect_profile.py /opt/couchbase-sync-gateway/bin/sync_gateway chdir=/home/sync_gateway/
    async: 3600
    poll: 0
    when: "'sync_gateway_index_writers' not in group_names"

- hosts: sync_gateway_index_writers
  any_errors_fatal: true
  remote_user: centos
  sudo: true

  # Copy machine stat collection script to sg_accels
  tasks:
  - name: copy the machine collection script
    copy: src=files/log_machine_stats.py dest=/home/sg_accel/ owner=sg_accel group=sg_accel mode=755
  # Start collecting machine stats, run async with an hour timeout, no polling
  - name: start stat collection
    shell: ./log_machine_stats.py chdir=/home/sg_accel/
    async: 3600
    poll: 0

  # Copy profile collection script to sg_accels
  - name: copy the profile collection script
    copy: src=files/sync_gateway_collect_profile.py dest=/home/sg_accel/ owner=sg_accel group=sg_accel mode=755
  # Start collecting profile, run async with an hour timeout, no polling
  - name: start profile collection
    shell: ./sync_gateway_collect_profile.py /opt/couchbase-sg-accel/bin/sg_accel chdir=/home/sg_accel/
    async: 3600
    poll: 0

- hosts: load_generators
  any_errors_fatal: true
  remote_user: centos

  # Deploy gateload script and start gateload
  tasks:
  - name: copy the run gateload script
    copy: src=files/run_gateload.sh dest=/home/centos/ owner=centos group=centos mode=0755
  - name: start gateload in screen
    shell: screen -d -m -S gateload ./run_gateload.sh
  - name: remove previous expvar json files
    shell: rm -rf expvar*.json
  - name: copy the expvar collection script
    copy: src=files/collect_expvars.sh dest=/home/centos/collect_expvars.sh owner=centos group=centos mode=0755
  - name: collect expvar json in screen
    shell: screen -d -m -S gateload_expvars ./collect_expvars.sh


