---
# Provision sync_gateway_vms
- hosts: sync_gateways
  any_errors_fatal: true
  remote_user: root
  sudo: yes

  tasks:
  - name: stop sync_gateway service
    service: name=sync_gateway state=stopped
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  - name: stop sync_gateway for CentOS 6
    shell: /sbin/initctl stop sync_gateway
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
    ignore_errors: yes
  - name: verify sync_gateway not listening on port
    wait_for: port=4985 delay=1 state=stopped
