---
- hosts: sync_gateways
  remote_user: centos
  any_errors_fatal: true
  sudo: true
  tasks:

  # Fetch generated profile results
  tasks:
  - name: Fetch sync gateway profile
    fetch: src=/tmp/sync_gateway_profile.tar.gz dest=/tmp/sync_gateway_profile/{{ inventory_hostname }}/ fail_on_missing=yes flat=yes
  - name: Tell user where to find the profile data
    debug: msg="Profile data has been saved in /tmp/sync_gateway_profile.tar.gz"

