---
# Remove sync_gateway
- hosts: sync_gateways
  sudo: true

  tasks:
  # Delete previous artifacts
  - name: delete downloads directory
    shell: rm -rf /tmp/*
  - name: delete user home files
    shell: rm -rf /home/centos/*
  - include: tasks/remove-sync-gateway.yml
  - include: tasks/remove-sg-accel.yml

# Flush server buckets
- hosts: couchbase_servers
  any_errors_fatal: true
  sudo: true
  vars:
    # Primary node
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_ssh_host }}"

    # Current node
    couchbase_server_node: "{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"

    couchbase_server_home_path: /opt/couchbase
    couchbase_server_admin_port: 8091
    couchbase_server_admin: Administrator
    couchbase_server_password: password

    couchbase_server_bucket_type: couchbase
    couchbase_server_bucket_port: 11211
    couchbase_server_bucket_replica: 1
    couchbase_server_cluster_ram: "{{ ((ansible_memtotal_mb|int)*0.8)|int }}"
    couchbase_server_bucket_ram: "{{ ((couchbase_server_cluster_ram|int)*0.5)|int }}"

  tasks:
  - include: tasks/flush-server-buckets.yml

# Create sync_gateway user
- hosts: sync_gateways
  sudo: true
  any_errors_fatal: true
  tasks:
  - include: tasks/create-sync-gateway-user.yml
    when: "'sync_gateway_index_writers' not in group_names"

# Create sg_accel user
- hosts: sync_gateway_index_writers
  sudo: true
  any_errors_fatal: true
  tasks:
  - include: tasks/create-sg-accel-user.yml

# Download sync_gateway package
- hosts: sync_gateways
  any_errors_fatal: true
  sudo: true

  vars:
    couchbase_sync_gateway_package_base_url:
    couchbase_sync_gateway_package:
    couchbase_sync_gateway_package_url: "{{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sync_gateway_package }}"
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_ssh_host }}"

  tasks:
  - debug: msg="Downloading sync_gateway v. {{ couchbase_sync_gateway_package_url }}"
  - name: Download sync_gateway rpm
    get_url: url={{ couchbase_sync_gateway_package_url }} dest=/tmp/{{ couchbase_sync_gateway_package }}
    when: "'sync_gateway_index_writers' not in group_names"

# Download sg accel package
- hosts: sync_gateway_index_writers
  any_errors_fatal: true
  sudo: true

  vars:
    couchbase_sync_gateway_package_base_url:
    couchbase_sg_accel_package:
    couchbase_sg_accel_package_url: "{{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sg_accel_package }}"
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_ssh_host }}"

  tasks:
  - debug: msg="Downloading sg_accel v. {{ couchbase_sg_accel_package_url }}"
  - name: Download sg_accel rpm
    get_url: url={{ couchbase_sg_accel_package_url }} dest=/tmp/{{ couchbase_sg_accel_package }}

# Deploy non writer sync_gateway configs
- hosts: sync_gateways
  any_errors_fatal: true
  sudo: true
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_ssh_host }}"
    is_index_writer: "false"
  tasks:
  - include: tasks/deploy-sync-gateway-config.yml
    when: "'sync_gateway_index_writers' not in group_names"

# Deploy sg_accel index writer configs
- hosts: sync_gateway_index_writers
  sudo: true
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_ssh_host }}"
    is_index_writer: "true"
  tasks:
  - include: tasks/deploy-sg-accel-config.yml

# Install and launch sync_gateway service
- hosts: sync_gateways
  any_errors_fatal: true
  sudo: true
  tasks:
  # Install and start service
  - name: Install sync_gateway rpm
    shell: rpm -i /tmp/{{ couchbase_sync_gateway_package }}
    when: "'sync_gateway_index_writers' not in group_names"
  - name: wait until sync gateway to listen on port
    wait_for: port=4985 delay=2 timeout=120
    when: "'sync_gateway_index_writers' not in group_names"

# Install and launch sg_accel service
- hosts: sync_gateway_index_writers
  any_errors_fatal: true
  sudo: true
  tasks:
  # Install and start service
  - name: Install sg_accel rpm
    shell: rpm -i /tmp/{{ couchbase_sg_accel_package }}
  - name: wait for sg_accel to listen on port
    wait_for: port=4985 delay=2 timeout=120
