---
# Remove sync_gateway
- hosts: sync_gateways
  sudo: true

  tasks:

  - include: tasks/remove-sync-gateway.yml

# Flush server buckets
- hosts: couchbase_servers
  any_errors_fatal: true
  sudo: true
  vars:
    # Primary node
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_ssh_host }}"
    # Current node
    couchbase_server_node: "{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"

    couchbase_server_home_path: /opt/couchbase
    couchbase_server_admin_port: 8091
    couchbase_server_admin: Administrator
    couchbase_server_password: password

    couchbase_server_bucket_type: couchbase
    couchbase_server_bucket_port: 11211
    couchbase_server_bucket_replica: 1
    couchbase_server_cluster_ram: "{{ ((ansible_memtotal_mb|int)*0.8)|int }}"
    couchbase_server_bucket_ram: "{{ ((couchbase_server_cluster_ram|int)*0.5)|int }}"

  tasks:
  - include: tasks/flush-server-buckets.yml

# Download source and build
- hosts: sync_gateways
  any_errors_fatal: true
  sudo: true
  vars:
    branch:

  tasks:
  - name: clone sync gateway git repo
    git: repo=https://github.com/couchbase/sync_gateway.git
         dest=/home/centos/sync_gateway
         recursive=no
  - name: checkout feature branch
    shell: git checkout {{ branch }} chdir=/home/centos/sync_gateway
  - name: update submodules
    shell: git submodule init && git submodule update chdir=/home/centos/sync_gateway
  - name: build sync gateway
    shell: ./build.sh chdir=/home/centos/sync_gateway

# Install and start service
- hosts: sync_gateways
  sudo: true
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_ssh_host }}"

  tasks:
  # Create sync_gateway user, install and start service
  - include: tasks/start-sync-gateway.yml

