---
- name: Wait for port 22 to be ready
  hosts: sync_gateway_index_writers
  gather_facts: False
  tasks:
  - wait_for: port=22 delay=2

# Deploy sync gateway configs (index writers)
- hosts: sync_gateway_index_writers
  any_errors_fatal: true
  sudo: true
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
    webhook_ip: "{{ hostvars[groups.webhook_ip[0]].ansible_host }}"
    is_index_writer: "true"
  tasks:
  - include: tasks/deploy-sg-accel-config.yml

- hosts: sync_gateway_index_writers
  any_errors_fatal: true
  sudo: true
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
  tasks:
  - include: tasks/start-sg-accel.yml