---
- hosts: load_generators
  any_errors_fatal: true
  tasks:
  - name: GATELOAD | go get gateload
    shell: GOPATH=/opt/go go get -u -v github.com/couchbaselabs/gateload
    sudo: true

  - name: GATELOAD | Symlink gateload into /usr/local/bin
    file: src=/opt/go/bin/gateload dest=/usr/local/bin/gateload owner=centos group=centos state=link
    sudo: true

  - name: GATELOAD | Sysctl file to increase available port range for outgoing socket connections
    copy: src=files/sysctld.conf dest=/etc/sysctl.d/20-increase-port-range.conf owner=root group=root mode=0644
    sudo: true

  - name: GATELOAD | Shell cmd to increase available port range for outgoing socket connections
    shell: sysctl --system
    sudo: true



