---
# Deploy sync gateway configs
- hosts: sync_gateways
  tasks:
  - include: tasks/delete-sync-gateway-artifacts.yml
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Amazon" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - include: tasks/delete-sync-gateway-artifacts-windows.yml
    when: ansible_os_family == "Windows"