---
# Deploy SG config
- hosts: sync_gateways
  any_errors_fatal: true

  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
    # hack until mobile-testkit/issues/406 allows any sync gateway to be referenced
    sync_gateway_node: "{{ hostvars[groups.sync_gateways[0]].ansible_host }}"
    webhook_ip: "{{ hostvars[groups.webhook_ip[0]].ansible_ssh_host }}"
    is_index_writer: "false"
    server_scheme:
    server_port:
    autoimport:
    xattrs:
    sslcert:
    sslkey:
    logging:
    cacertpath:
    x509_auth:
    x509_certs_dir:
    server_tls_skip_verify:
    disable_admin_auth:
    certpath:
    keypath:

  tasks:
  - include: tasks/stop-sync-gateway.yml
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Amazon" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" or ansible_distribution == "MacOSX"

  - include: tasks/stop-sync-gateway-windows.yml
    when: ansible_os_family == "Windows"

  - include: tasks/deploy-sync-gateway-config.yml
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - include: tasks/start-sync-gateway.yml
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - include: tasks/deploy-sync-gateway-config-macos.yml
    when: ansible_distribution == "MacOSX"

  - include: tasks/start-sync-gateway-macos.yml
    when: ansible_distribution == "MacOSX"

  - include: tasks/deploy-sync-gateway-config-windows.yml
    when: ansible_os_family == "Windows"

  - include: tasks/start-sync-gateway-windows.yml
    when: ansible_os_family == "Windows"

# Deploy SG Accel config
- hosts: sg_accels
  any_errors_fatal: true
  become: yes
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
    # hack until mobile-testkit/issues/406 allows any sync gateway to be referenced
    sync_gateway_node: "{{ hostvars[groups.sync_gateways[0]].ansible_host }}"
    webhook_ip: "{{ hostvars[groups.webhook_ip[0]].ansible_ssh_host }}"
    is_index_writer: "true"
    server_scheme:
    server_port:
    autoimport:
    xattrs:
    sslcert:
    sslkey:
    logging:

  tasks:
    - include: tasks/stop-sg-accel.yml
    - include: tasks/deploy-sg-accel-config.yml
    - include: tasks/start-sg-accel.yml
