---

- hosts: pool
  any_errors_fatal: true
  become: yes
  tasks:
   - name: Install telegraf from remote RPM
     yum: name=https://dl.influxdata.com/telegraf/releases/telegraf-1.0.0.x86_64.rpm state=present

- hosts: load_balancers
  vars:
     grafana_db: "{{ lookup('env','GRAFANA_DB') }}"
  any_errors_fatal: true
  become: yes
  tasks:
   - name: Configure telegraf for load_balancers
     template: src=files/telegraf-nginx.conf dest=/etc/telegraf/telegraf.conf owner=root group=root mode=0644

- hosts: load_generators
  vars:
     grafana_db: "{{ lookup('env','GRAFANA_DB') }}"
  any_errors_fatal: true
  become: yes
  tasks:
   - name: Configure telegraf for load_generators
     template: src=files/telegraf-gateload.conf dest=/etc/telegraf/telegraf.conf owner=root group=root mode=0644

- hosts: sync_gateways
  vars:
     grafana_db: "{{ lookup('env','GRAFANA_DB') }}"
  any_errors_fatal: true
  become: yes
  tasks:
   - name: Configure telegraf for sync_gateways
     template: src=files/telegraf-sync-gateway.conf dest=/etc/telegraf/telegraf.conf owner=root group=root mode=0644

   - name: Copy custom telegraf binary with syncgateway plugin
     copy: src=files/telegraf dest=/usr/bin/telegraf owner=root group=root mode=0775

- hosts: couchbase_servers
  vars:
     grafana_db: "{{ lookup('env','GRAFANA_DB') }}"
  any_errors_fatal: true
  become: true
  tasks:
   - name: Configure telegraf for couchbase_servers
     template: src=files/telegraf-couchbase-server.conf dest=/etc/telegraf/telegraf.conf owner=root group=root mode=0644

- hosts: load_generators:load_balancers:sync_gateways:couchbase_servers
  any_errors_fatal: true
  become: true
  tasks:
   - name: Restart telegraf service
     action: shell service telegraf restart
