---
- hosts: couchbase_servers
  any_errors_fatal: true
  serial: 1
  vars:
    couchbase_server_primary_node: "{{ inventory_hostname }}"
  connection: local
  tasks:
    - shell: echo {{couchbase_server_primary_node}} > ../../temp_couchbase_server_primary_node


- hosts: load_generators
  vars:
    gateload_node: "{{ inventory_hostname }}"
  connection: local
  tasks:
    - shell: echo {{gateload_node}} > ../../temp_gateload_node


- hosts: 127.0.0.1
  any_errors_fatal: true
  connection: local
  tasks:
  - name: set couchbase_server_primary_node variable
    set_fact:
      couchbase_server_primary_node: "{{ lookup('file', '../../temp_couchbase_server_primary_node') }}"

  - name: test of local copy
    action: copy src=./files/cbagent_config_template.conf dest=../../temp_cbagent_config_template.conf

  - shell: sed -i -e 's/MASTER_HOST/{{ couchbase_server_primary_node }}/g' ../../temp_cbagent_config_template.conf


- hosts: couchbase_servers:sync_gateways:load_generators
  any_errors_fatal: true
  sudo: true
  vars:
    splunkforwarder_package: splunkforwarder-6.2.2-255606-linux-2.6-x86_64.rpm
    splunkforwarder_url: http://www.splunk.com/page/download_track?file=6.2.2/universalforwarder/linux/{{ splunkforwarder_package }}&ac=adwords-syslog&wget=true&name=wget&platform=Linux&architecture=x86_64&version=6.2.2&product=splunk&typed=release
    forward_server:
    forward_server_auth:
    splunk_add_on_for_unix_and_linux: splunk-add-on-for-unix-and-linux_512.tgz
    splunk_add_on_for_unix_and_linux_url: http://couchbase-mobile.s3.amazonaws.com/perfcluster-aws/splunk_unix_linux_add_on/{{ splunk_add_on_for_unix_and_linux }}
    inputs_conf: /opt/splunkforwarder/etc/apps/Splunk_TA_nix/local/inputs.conf
  tasks:
  - name: kill splunkforwarder
    shell: pkill -9 splunk
    sudo: true
    ignore_errors: yes
  - name: uninstall splunkforwarder
    shell: rpm -e splunkforwarder && rm -rf /opt/splunkforwarder/
    sudo: true
    ignore_errors: yes
  - name: Download splunkforwarder
    get_url: url={{ splunkforwarder_url }} dest=/tmp/{{ splunkforwarder_package }}
  - name: install splunkforwarder
    shell: cd /tmp/ && sudo rpm -i {{ splunkforwarder_package }}
  - name: start splunkforwarder
    shell: /opt/splunkforwarder/bin/splunk start --accept-license
    sudo: true
  - debug: msg="Splunk Forward Server {{ forward_server }} using credentials {{ forward_server_auth }}"
  - name: add forward-server to Splunk forwarder
    shell: /opt/splunkforwarder/bin/splunk add forward-server {{ forward_server }} -auth {{ forward_server_auth }}
    sudo: true
  - name: Test the forwarder
    shell: /opt/splunkforwarder/bin/splunk list forward-server
    sudo: true

  - name: download 'Splunk Add-on for Unix and Linux'
    get_url: url={{ splunk_add_on_for_unix_and_linux_url }} dest=/tmp/{{ splunk_add_on_for_unix_and_linux }}
  - name: extract archive 'Splunk Add-on for Unix and Linux'
    shell: tar -C /opt/splunkforwarder/etc/apps/ -xvf /tmp/{{ splunk_add_on_for_unix_and_linux }}
  - name: copy Splunk Add-on for Unix and Linux' configs
    shell: mkdir /opt/splunkforwarder/etc/apps/Splunk_TA_nix/local && cp /opt/splunkforwarder/etc/apps/Splunk_TA_nix/default/inputs.conf {{ inputs_conf }}

  - name: enable vmstat in "inputs.conf"
    shell: sed -i ""$(($(awk '/vmstat\.sh./{ print NR; exit }' {{ inputs_conf }})+5))"s/.*/disabled = 0/" {{ inputs_conf }}
    sudo: true
  - name: enable iostat in "inputs.conf"
    shell: sed -i ""$(($(awk '/iostat\.sh/{ print NR; exit }' {{ inputs_conf }})+5))"s/.*/disabled = 0/" {{ inputs_conf }}
    sudo: true
  - name: enable ps in "inputs.conf"
    shell: sed -i ""$(($(awk '/ps\.sh/{ print NR; exit }' {{ inputs_conf }})+5))"s/.*/disabled = 0/" {{ inputs_conf }}
    sudo: true
  - name: enable top in "inputs.conf"
    shell: sed -i ""$(($(awk '/top\.sh/{ print NR; exit }' {{ inputs_conf }})+5))"s/.*/disabled = 0/" {{ inputs_conf }}
    sudo: true
  - name: enable netstat in "inputs.conf"
    shell: sed -i ""$(($(awk '/netstat\.sh/{ print NR; exit }' {{ inputs_conf }})+5))"s/.*/disabled = 0/" {{ inputs_conf }}
    sudo: true
  - name: enable cpu in "inputs.conf"
    shell: sed -i ""$(($(awk '/cpu\.sh/{ print NR; exit }' {{ inputs_conf }})+5))"s/.*/disabled = 0/" {{ inputs_conf }}
    sudo: true
  - name: restart splunkforwarder
    shell: /opt/splunkforwarder/bin/splunk restart
    sudo: true

- hosts: sync_gateways
  any_errors_fatal: true
  sudo: true
  vars:
    forward_server_auth:
  tasks:
  - name: Capture sync gateway logs
    shell: /opt/splunkforwarder/bin/splunk add monitor /home/sync_gateway/logs -index main -sourcetype sync_gateway_logs -auth {{ forward_server_auth }}
  - name: kill collect_url_requests.sh
    shell: pkill -f "collect_url_requests.sh"
    ignore_errors: yes
  - name: copy collect_url_requests.sh to host
    template: src=./files/collect_url_requests.sh dest=/home/centos/collect_url_requests.sh owner=sync_gateway group=sync_gateway mode=0777 force=true
  - name: Collect _expvar logs
    shell: ((nohup /home/centos/collect_url_requests.sh -r http://localhost:4985/_expvar -f /home/centos/_expvar.logs -t 60 1>/dev/null 2>&1) &)
  - name: Capture _expvar logs
    shell: /opt/splunkforwarder/bin/splunk add monitor /home/centos/_expvar.logs -index main -sourcetype sync_gateway_expvars  -auth {{ forward_server_auth }}

- hosts: load_generators
  any_errors_fatal: true
  vars:
    gateload_node: "{{ inventory_hostname }}"
    forward_server_auth:
  tasks:
  - name: set primary_gateload_node variable
    set_fact:
      primary_gateload_node: "{{ lookup('file', '../../temp_gateload_node') }}"
  - file: path=/home/centos/logs state=directory
  - name: Capture gateload logs
    shell: /opt/splunkforwarder/bin/splunk add monitor /home/centos/logs -index main -sourcetype gateload_logs -auth {{ forward_server_auth }}
    sudo: true
  - name: kill collect_url_requests.sh
    shell: pkill -f "collect_url_requests.sh"
    sudo: true
    ignore_errors: yes
  - name: copy collect_url_requests.sh to host
    template: src=./files/collect_url_requests.sh dest=/home/centos/collect_url_requests.sh owner=centos mode=0777 force=true
  - name: Collect debug/vars logs
    shell: ((nohup /home/centos/collect_url_requests.sh -r http://localhost:9876/debug/vars -f /home/centos/debug_vars.logs -t 60 1>/dev/null 2>&1) &)
  - pause: seconds=5
  - name: Capture debug/vars logs
    shell: /opt/splunkforwarder/bin/splunk add monitor /home/centos/debug_vars.logs -index main -sourcetype gateload_expvars  -auth {{ forward_server_auth }}
    sudo: true

  - name: Clone cbagent into /home/centos/cbagent
    git: repo=https://github.com/andreibaranouski/cbagent
         dest=/home/centos/cbagent
         force=yes
    when: primary_gateload_node == gateload_node
  - name: install pip
    shell: easy_install pip
    when: primary_gateload_node == gateload_node
    sudo: true
  - name: install python-devel
    yum: pkg=python-devel state=latest
    sudo: true
  - name: install development tools
    shell: yum groupinstall -y 'Development Tools'
    sudo: true
  - name: Download couchbase.repo
    get_url: url=http://packages.couchbase.com/rpm/couchbase-centos62-x86_64.repo dest=/etc/yum.repos.d/couchbase.repo
    when: primary_gateload_node == gateload_node
    sudo: true
  - name: yum check-update
    shell: yum check-update
    when: primary_gateload_node == gateload_node
    ignore_errors: yes
    sudo: true
  - name: install libcouchbase2-libevent libcouchbase-devel
    shell: sudo yum install -y libcouchbase2-libevent libcouchbase-devel --skip-broken
    when: primary_gateload_node == gateload_node
    sudo: true
  - name: install cbagent requirements
    shell: cd /home/centos/cbagent && pip install -r requirements.txt
    when: primary_gateload_node == gateload_node
    sudo: true
  - name: copy temp_cbagent_config_template.conf to host
    template: src=../../temp_cbagent_config_template.conf dest=/home/centos/cbagent/temp_cbagent_stats_monitor.spec force=true
    when: primary_gateload_node == gateload_node
  - name: kill cbagent
    shell: pkill -f cbagent
    ignore_errors: yes
    when: primary_gateload_node == gateload_node
  - name: Remove previous stats
    shell: "rm -rf /tmp/stats_folder/*"
    when: primary_gateload_node == gateload_node
  - name: Run cbagent ns stats
    shell: "cd /home/centos/cbagent/ && nohup python -m cbagent --ns temp_cbagent_stats_monitor.spec 1>/dev/null 2>&1 &"
    when: primary_gateload_node == gateload_node
  - name: Run cbagent active tasks stats
    shell: "cd /home/centos/cbagent/ && nohup python -m cbagent --at temp_cbagent_stats_monitor.spec >/dev/null 2>&1 &"
    when: primary_gateload_node == gateload_node
  - name: Capture couchbase stats
    shell: /opt/splunkforwarder/bin/splunk add monitor /tmp/stats_folder -index main -sourcetype cbagent -auth {{ forward_server_auth }}
    when: primary_gateload_node == gateload_node
    sudo: true

  - file: path=/home/projects/sg-gatling-load/themes/gateload-sim/target/gatling/results state=directory
    sudo: true
  - name: Capture gateload logs
    shell: /opt/splunkforwarder/bin/splunk add monitor /home/projects/sg-gatling-load/themes/.../target/gatling/results/.../simulation.log -index main -sourcetype gatling_results -auth {{ forward_server_auth }}
    sudo: true


- hosts: couchbase_servers
  any_errors_fatal: true
  sudo: true
  vars:
    forward_server_auth:
  tasks:
  - name: Capture couchbase logs
    #shell: /opt/splunkforwarder/bin/splunk add monitor /opt/couchbase/var/lib/couchbase/logs -index main -sourcetype couchbase_logs -auth {{ forward_server_auth }}
    shell: /opt/splunkforwarder/bin/splunk add monitor /opt/couchbase/var/lib/couchbase/logs/error.log -index main -sourcetype couchbase_logs -auth {{ forward_server_auth }}
    shell: /opt/splunkforwarder/bin/splunk add monitor /opt/couchbase/var/lib/couchbase/logs/mapreduce_errors.log -index main -sourcetype couchbase_logs -auth {{ forward_server_auth }}
