---
# Remove sync_gateway
- hosts: sg_accels
  become: yes

  vars:
    couchbase_sync_gateway_package_base_url:
    couchbase_sync_gateway_package:
    couchbase_sync_gateway_package_url: "{{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sync_gateway_package }}"

  tasks:
  - include: tasks/stop-sg-accel.yml
  - include: tasks/remove-sg-accel.yml
  - include: tasks/clean-users.yml

  # Check no sync_gateways or accels running
  - name: SG ACCEL | verify no service on 4985
    wait_for: port=4985 delay=1 state=stopped
    when: ansible_distribution == "CentOS"

# Create sg_accel user
- hosts: sg_accels
  become: yes
  any_errors_fatal: true
  tasks:
  - include: tasks/create-sg-accel-user.yml

# Download sg accel package
- hosts: sg_accels
  become: yes
  any_errors_fatal: true

  vars:
    couchbase_sync_gateway_package_base_url:
    couchbase_sg_accel_package:
    couchbase_sg_accel_package_url: "{{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sg_accel_package }}"
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"

  tasks:
  - name: SG Accel | Download sg_accel rpm {{ couchbase_sg_accel_package_url }}
    get_url: url={{ couchbase_sg_accel_package_url }} dest=/tmp/{{ couchbase_sg_accel_package }}

# Install sg_accel
- hosts: sg_accels
  become: yes
  any_errors_fatal: true
  tasks:
  - include: tasks/install-sg-accel.yml

# Deploy sg_accel index writer configs
- hosts: sg_accels
  become: yes
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
    # hack until mobile-testkit/issues/406 allows any sync gateway to be referenced
    sync_gateway_node: "{{ hostvars[groups.sync_gateways[0]].ansible_host }}"
    is_index_writer: "true"
  tasks:
  - include: tasks/deploy-sg-accel-config.yml

# Launch sg_accel service
- hosts: sg_accels
  become: yes
  any_errors_fatal: true
  tasks:
  - include: tasks/start-sg-accel.yml
