global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
  - '/etc/prometheus/rules/*'

scrape_configs:
  - job_name: swg
    metrics_path: /_metrics
    scheme: http
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - 172.23.136.116:4986
    basic_auth:
      username: Administrator
      password: password
