---
# Kill sync_gateway
- hosts: sync_gateways
  any_errors_fatal: true

  tasks:
  - include: tasks/stop-sync-gateway.yml
    become: yes
    when: ansible_distribution == "CentOS"

  - include: tasks/stop-sync-gateway-windows.yml
    when: ansible_os_family == "Windows"

  # Delete logs and .pindex files
  - include: tasks/delete-sync-gateway-artifacts.yml
    become: yes
    when: ansible_distribution == "CentOS"

  - include: tasks/delete-sync-gateway-artifacts-windows.yml
    when: ansible_os_family == "Windows"

# Deploy sync gateway configs
- hosts: sync_gateways
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
    # hack until mobile-testkit/issues/406 allows any sync gateway to be referenced
    sync_gateway_node: "{{ hostvars[groups.sync_gateways[0]].ansible_host }}"
    webhook_ip: "{{ hostvars[groups.webhook_ip[0]].ansible_ssh_host }}"
    is_index_writer: "false"
    server_scheme:
    server_port:
    autoimport:
    xattrs:
  tasks:
  - include: tasks/deploy-sync-gateway-config.yml
    become: yes
    when: ansible_distribution == "CentOS"

  - include: tasks/deploy-sync-gateway-config-windows.yml
    when: ansible_os_family == "Windows"

# Deploy sync gateway configs (index writers)
- hosts: sg_accels
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
    # hack until mobile-testkit/issues/406 allows any sync gateway to be referenced
    sync_gateway_node: "{{ hostvars[groups.sync_gateways[0]].ansible_host }}"
    webhook_ip: "{{ hostvars[groups.webhook_ip[0]].ansible_host }}"
    is_index_writer: "true"
    server_scheme:
    server_port:
    autoimport:
    xattrs:
  tasks:
  - include: tasks/deploy-sync-gateway-config.yml
    become: yes
    when: ansible_distribution == "CentOS"

  - include: tasks/deploy-sync-gateway-config-windows.yml
    when: ansible_os_family == "Windows"

# Start sync_gateway
- hosts: sync_gateways
  any_errors_fatal: true

  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
  tasks:
  - include: tasks/start-sync-gateway.yml
    become: yes
    when: ansible_distribution == "CentOS"

  - include: tasks/start-sync-gateway-windows.yml
    when: ansible_os_family == "Windows"