---
- hosts: load_generators
  any_errors_fatal: true
  sudo: yes

  vars:
    number_of_pullers: 0
    number_of_pushers: 7500

  tasks:

  - name: Remove local simulation log storage
    local_action: file  path=/tmp/sg-gatling-load/ state=absent
    run_once: true
    sudo: no

  - name: Run sg-gatling-load theme
    shell: mvn install -e -P gateload-sim -DnumPullers={{ number_of_pullers }} -DnumPushers={{ number_of_pushers }} -DrampUpIntervalMs=600000 > gatling-theme.log
    args:
      chdir: /home/projects/sg-gatling-load/
