- name: Windows - Start TestServer
  hosts: windows
  vars:
    binary_path:
  tasks:
    - debug: msg="Starting the Testserver  {{ binary_path }}"
    - name: Start TestServer
      win_nssm:
        name: TestServerC
        application: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ binary_path }}
        state: started