
- name: Start TestServer
  hosts: testserver
  vars:
    binary_path:

  tasks:
    - debug: msg="Starting the TestService  {{binary_path}}"
    - name: Start TestServer
      shell: "nohup {{ binary_path }}/ctestserver/testserver &"
      args:
        chdir: "{{ binary_path }}/ctestserver"
