- name: Windows - Stop TestServer
  hosts: windows
  vars:
    log_full_path:

  tasks:
    - debug: msg="Stoping the Testserver "
    - debug: msg="Copying logs at - {{ log_full_path }}"
    - name: Stop TestServer
      win_command: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ binary_path }}\testserver.exe /c