---
# Download sync_gateway package
- hosts: sync_gateways
  any_errors_fatal: true

  vars:
    sync_gateway_config_filepath:
    couchbase_sync_gateway_package_base_url:
    couchbase_sync_gateway_package:
    couchbase_sync_gateway_package_url: "{{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sync_gateway_package }}"
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"

  tasks:
  - debug: msg="Downloading sync_gateway v. {{ couchbase_sync_gateway_package_url }}"
  - name: SYNC GATEWAY |  Download sync_gateway rpm
    get_url: url={{ couchbase_sync_gateway_package_url }} dest=/tmp/{{ couchbase_sync_gateway_package }} validate_certs=False


# Install and launch sync_gateway service
- hosts: sync_gateways
  any_errors_fatal: true
  become: yes
  tasks:
  - include: tasks/stop-sync-gateway.yml

  tasks:
  # update and start service
  - name: SYNC GATEWAY | Install sync_gateway rpm
    shell: rpm -U --force /tmp/{{ couchbase_sync_gateway_package }}

  - name: SYNC GATEWAY | wait until sync gateway to listen on port
    wait_for: port=4985 timeout=120

  - debug: msg="Completed upgrading sync gateway {{ hostvars[inventory_hostname]['ansible_host'] }}"

