  - name: BLOCKPORTS | Verify that port is blocked in iptables
    shell: iptables-save | grep -- "OUTPUT -p tcp -m tcp --dport {{ port }} -j DROP" | wc -l
    register: iptablesrules

  - name: BLOCKPORTS | drop tcp {{ port }}
    shell: iptables -I OUTPUT -p tcp --dport {{ port }} -j DROP
    when: iptablesrules|length >= 1

  - name: BLOCKPORTS | drop udp {{ port }}
    shell: iptables -I OUTPUT -p udp --dport {{ port }} -j DROP
    when: iptablesrules|length >= 1

  - name: BLOCKPORTS | install iptables-services
    shell: yum -y install iptables-services
    when: iptablesrules|length >= 1

  - name: BLOCKPORTS | save iptables after dropping
    shell: service iptables save
    when: iptablesrules|length >= 1

  - name: BLOCKPORTS | restart iptables after dropping
    shell: service iptables restart
    when: iptablesrules|length >= 1
