# Create the provided directory
- name: SYNC GATEWAY | Create sync_gateway directory {{ directory }} on non-windows
  become: yes
  file: path={{ directory }} state=directory
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Amazon" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" or ansible_distribution == "MacOSX"

- name: SYNC GATEWAY | Change the mode for sync_gateway directory {{ directory }} on non-windows
  become: yes
  file: path={{ directory }} mode='777'
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Amazon" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" or ansible_distribution == "MacOSX"

- name: SYNC GATEWAY | Create sync_gateway directory {{ directory }} on windows
  become: no
  win_file:
    path: "{{ directory }}"
    state: directory
  when: ansible_os_family == "Windows"

- name: SYNC GATEWAY | Change the permissions on windows
  become: no
  win_shell: icacls {{ directory }} /grant Everyone:F
  when: ansible_os_family == "Windows"
