- name: SYNC GATEWAY | Copy sync gateway config to host
  become: yes
  template: src={{ sync_gateway_config_filepath }} dest=/home/sync_gateway/sync_gateway.json owner=sync_gateway group=sync_gateway mode=0644 force=true

# Deleting cert directory if exist
- name: Deleting /home/sync_gateway/certs directory
  file:
    state: absent
    path: /home/sync_gateway/certs/
  become: yes
  when: x509_auth

# - name: Deleting /home/sync_gateway/certs.zip
#   file:
#     state: absent
#     path: /home/sync_gateway/certs.zip
#   become: yes
#   when: x509_auth

# # Copy certs to /home/sync_gateway dir
# - name: Copying certs.zip to /home/sync_gateway directory
#   copy:
#     owner: sync_gateway
#     src: /tmp/certs.zip
#     dest: /home/sync_gateway/
#     remote_src: yes
#     force: yes
#   when: x509_auth
#   become: yes


# # unzip certs.zip
# - name: Unzipping certs.zip
#   shell: unzip /home/sync_gateway/certs.zip -d /home/sync_gateway/certs
#   when: x509_auth
#   become: yes

- name: SYNC GATEWAY | Create certs directory on sync gateway home directory
  become: yes
  shell : mkdir /home/sync_gateway/certs
  when: x509_auth

- name: SYNC GATEWAY | Deploying cert path for x509
  become: yes
  template: src="{{ x509_certs_dir }}/chain.pem" dest=/home/sync_gateway/certs/chain.pem owner=sync_gateway group=sync_gateway mode=0644 force=true
  when: certpath is defined and x509_auth

- name: SYNC GATEWAY | Deploying keypath for x509
  become: yes
  template: src="{{ x509_certs_dir }}/pkey.key" dest=/home/sync_gateway/certs/pkey.key owner=sync_gateway group=sync_gateway mode=0644 force=true
  when: keypath is defined and x509_auth

- name: SYNC GATEWAY | Deploying cacertpath for x509
  become: yes
  template: src="{{ x509_certs_dir }}/ca.pem" dest=/home/sync_gateway/certs/ca.pem owner=sync_gateway group=sync_gateway mode=0644 force=true
  when: cacertpath is defined and x509_auth

- name: SYNC GATEWAY | Change the mode permissions on Centos
  become: yes
  shell: chmod 777 /home/sync_gateway/certs/*.*
  when: x509_auth 

- name: SYNC GATEWAY | Check deployed config
  become: yes
  shell: cat /home/sync_gateway/sync_gateway.json
  register: out

- name: SYNC GATEWAY | Print deployed config
  debug: var=out.stdout

- name: SYNC GATEWAY | Deploying SSL Cert
  become: yes
  template: src="{{ sg_cert_path }}/sg_cert.pem" dest=/home/sync_gateway/sg_cert.pem owner=sync_gateway group=sync_gateway mode=0644 force=true
  when: sslcert is defined

- name: SYNC GATEWAY | Deploying SSL Private Key
  become: yes
  template: src="{{ sg_cert_path }}/sg_privkey.pem" dest=/home/sync_gateway/sg_privkey.pem owner=sync_gateway group=sync_gateway mode=0644 force=true
  when: sslkey is defined
