# Install and stop sg_accel service
- name: SG ACCEL | Install sg_accel on CentOS
  become: yes
  shell: rpm -i /tmp/{{ couchbase_sg_accel_package }}
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: SG ACCEL | Install sg_accel rpm
  become: yes
  shell: dpkg -i /tmp/{{ couchbase_sg_accel_package }}
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- include: stop-sg-accel.yml
