# Install and stop sync_gateway service
- name: SYNC GATEWAY | Install sync_gateway rpm
  become: yes
  shell: rpm -i /tmp/{{ couchbase_sync_gateway_package }}
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: SYNC GATEWAY | Install sync_gateway deb
  become: yes
  shell: dpkg -i /tmp/{{ couchbase_sync_gateway_package }}
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: SYNC GATEWAY | Install sync_gateway zip
  become: yes
  shell: |
    unzip /tmp/{{ couchbase_sync_gateway_package }} --directory /opt
  when: ansible_distribution == "MacOSX"

- include: stop-sync-gateway.yml