- debug: msg="Starting sg_accel with config {{ sync_gateway_config_filepath }}"

- name: SG ACCEL | Start sg_accel service on Windows
  win_service:
    name: SGAccel
    state: started

# There is no win_wait_for
# This workaround delegates port check to localhost
- name: SG ACCEL | Wait until sg_accel to listen on port
  wait_for:
    host={{ ansible_host }}
    port=4984
    timeout=600
  delegate_to: localhost
