- debug: msg="Starting sync_gateway with config {{ sync_gateway_config_filepath }}"
- name: start sync gateway service
  service: name=sync_gateway state=started
- name: wait until sync gateway to listen on port
  wait_for: port=4985 timeout=120

